LerningProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
  path('admin/', admin.site.urls),
  path('accounts/', include('django.contrib.auth.urls')),
  path('accounts/', include('accounts.urls')),
  path('',include('english.urls'))
]

if settings.DEBUG:
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

english/urls.py
from django.urls import path, re_path
from .views import index, detail, create, update, delete, page_settings, share_detail, not_found, s2dic, private_dic_page, PrivateDictionaryEditView, detail_by_id, public_en2jp_dic_page, public_en2jp_dic_page_from_sentence, private_history

app_name = "english"

urlpatterns = [
  path('',index, name='index'),
  path('create/',create, name='create'),
  path('not_found/',not_found, name='not_found'),
  path('share/<str:share_code>/', share_detail, name='share_detail'),
  path('detail_by_id/<int:id>/', detail_by_id, name='detail_by_id'),
  re_path(r'^create/(?P<slug>.+)/$', create, name='create_with_slug'),
  path('settings/',page_settings, name='page_settings'),
  re_path(r'^detail/(?P<username>[^/]+)/(?P<slug>.+)/$', detail, name='detail'),
  re_path(r'^update/(?P<username>[^/]+)/(?P<slug>.+)/$', update, name='update'),
  path('delete/<int:id>/', delete, name='delete'),
  path('s/<int:id>/', s2dic, name='s2dic'),
  path('private/detail/<int:pk>/', private_dic_page, name='private_dic_page'),
  # path('private/detail/<int:pk>/<str:source_id>/', private_dic_page, name='private_dic_page_with_source'),
  path('private/edit/<int:pk>/', PrivateDictionaryEditView.as_view(), name='private_dic_edit'),
  path('public/en2jp/<str:word>/', public_en2jp_dic_page, name='public_en2jp'),
  path('s/<int:source_id>/public/', public_en2jp_dic_page_from_sentence, name='public_en2jp_from_sentence'),
  path('private/history/', private_history, name='private_history'),
]

english/models.py
from django.db import models
from django.conf import settings
from accounts.models import CustomUser as User
# from django.utils.safestring import mark_safe
# from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
from language.english import POS_CHOICES, POS_DICTIONARY

class PageTable(models.Model):
  user = models.ForeignKey(User, on_delete=models.CASCADE)
  last_updated = models.DateTimeField(auto_now=True)
  slug = models.CharField(max_length=127)
  priority = models.FloatField(default=0)
  title = models.CharField(max_length=127)
  description = models.TextField(blank=True)
  share = models.BooleanField(default=False)
  share_code = models.CharField(
    max_length=127,
    null=True,
    blank=True,
    validators=[RegexValidator(r'^[a-zA-Z0-9]+$')],
    unique=True
  )
  def __str__(self):
    return self.title
  class Meta:
    constraints = [
      models.UniqueConstraint(
        fields=["user", "slug"],
        name="slug_unique"
      )
    ]

class PublicEn2JpDictionaryTable(models.Model):
  word = models.CharField(max_length=31, unique=True) 
  mean = models.CharField(max_length=255)

class SentenceTable(models.Model):
  page = models.ForeignKey(PageTable, on_delete=models.CASCADE)
  word = models.CharField(max_length=31)  # 文中の単語がそのまま入る
  lemma = models.CharField(max_length=31)  # 文中の単語の原型が入る
  pos = models.CharField(max_length=15, choices=POS_CHOICES)  # part of speech=品詞
  def pos_jp(self):
    return POS_DICTIONARY[self.pos]

class PrivateDictionaryTable(models.Model):
  user = models.ForeignKey(User, on_delete=models.CASCADE)
  word = models.CharField(max_length=127)  # 原則は原型, 小文字
  pos = models.CharField(max_length=31, choices=POS_CHOICES)  # part of speech=品詞
  star = models.BooleanField(default=False)
  mean_jp = models.TextField(blank=True)  # 初期値は辞書を参照するがユーザーが編集できる
  # memo = models.TextField(blank=True)
  last_access = models.DateTimeField(auto_now=True)  # 更新も含む
  last_source = models.ForeignKey(SentenceTable, on_delete=models.SET_NULL, null=True, blank=True)
  access_counter = models.IntegerField(default=0)
  # public_en2jp_dictionary = models.ForeignKey(PublicEn2JpDictionaryTable, on_delete=models.CASCADE, null=True, blank=True)
  class Meta:
    constraints = [
      models.UniqueConstraint(
        fields=["user", "word", "pos"],
        name="word_unique"
      )
    ]
  def pos_jp(self):
    return POS_DICTIONARY[self.pos]

english/forms.py
from django import forms
from django.forms import modelformset_factory
from .models import PageTable

class PageForm(forms.ModelForm):
  # sentence = forms.TextInput()
  # sentenceは必須ではない
  sentence = forms.CharField(
    widget=forms.Textarea(
      attrs={
        'style': 'width: 100%; height: auto;'
      }
    ) 
  )
  class Meta:
    model = PageTable
    fields = (
      "slug",
      "priority",
      "title",
      "description",
      "share",
      "share_code",
    )
    widgets = {
      'title': forms.TextInput(
        attrs={
          'style': 'width: 100%; height: auto; font-size: 2rem;'
        }
      ),
      'slug': forms.TextInput(
        attrs={
          'style': 'width: 500px;'
        }
      ),
      'share_code': forms.TextInput(
        attrs={
          'style': 'width: 500px;'
        }
      ),
      # 'description': forms.Textarea(
      'description': forms.TextInput(
        attrs={
          'style': 'width: 100%; height: auto;'
        }
      ),
    }

class PageSettingsForm(forms.ModelForm):
  class Meta:
    model = PageTable
    fields = ["title", "slug", "priority"]
    widgets = {
      'title': forms.TextInput(attrs={'style': 'width: 300px;'}),
      'slug': forms.TextInput(attrs={'style': 'width: 220px;'}),
      'priority': forms.NumberInput(attrs={"step":"0.1", "style": "width:70px;"}),
    }

PageSettingsFormSet = modelformset_factory(
  PageTable, 
  form=PageSettingsForm,
  extra=0
)

english/views.py
from django.shortcuts import render, get_object_or_404, redirect
from accounts.models import CustomUser as User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.urls import reverse, reverse_lazy
from django.views.generic import UpdateView
# from django.views.generic import TemplateView
from django.core.paginator import Paginator
from django.conf import settings
from .models import PageTable, PrivateDictionaryTable, SentenceTable, PublicEn2JpDictionaryTable
from .forms import PageForm, PageSettingsFormSet
import random
from urllib.parse import quote
# 独自ライブラリ
from tree import Tree, gen_tree_htmls, gen_pages_ordered_by_tree
from language.english import text2SentenceTable, sentence2html, POS_DICTIONARY

def index(request):  # トップのページ
  if request.user.is_authenticated:
    pages = PageTable.objects.filter(Q(user__is_superuser=True) | Q(user=request.user)).order_by("-last_updated")
  else:
    pages = PageTable.objects.filter(user__is_superuser=True).order_by("-last_updated")
  context = {
    "tree_htmls":gen_tree_htmls(request, User, PageTable, a_white=False),
    "nav_tree_htmls":gen_tree_htmls(request, User, PageTable, a_white=True),
    "pages": pages
  }
  return render(request, 'english/index.html', context)

def share_detail(request, share_code):  # 英文のページを共有URLからアクセスした場合
  try:
    page = PageTable.objects.get(share_code=share_code)
  except PageTable.DoesNotExist:
    return not_found(request)
  return detail(request, page.user.username, page.slug, share=True)

def detail_by_id(request, id):  # 英文のページをID指定でアクセスした場合
  page = get_object_or_404(PageTable, pk=id)
  return detail(request, page.user.username, page.slug)

def detail(request, username, slug, share=False):  # 英文のページをユーザー名とスラッグでアクセスした場合
  try:
    user = User.objects.get(username=username)
    page = PageTable.objects.get(user=user, slug=slug)
  except User.objects.model.DoesNotExist:
    return not_found(request)
  except PageTable.DoesNotExist:
    if request.user.is_authenticated:
      if user == request.user:
        return redirect("english:create_with_slug",slug=slug)
      else:
        print("user != request.user")
        return not_found(request)
    else:
      print("not request.user.is_authenticated")
      return not_found(request)
  if not share and page.user != request.user and not user.is_superuser:
    print("not share and page.user != request.user and not user.is_superuser")
    return not_found(request)
  if page.user == request.user:
    edit = True
  else:
    edit = False
  if page.share:
    share_url = f"{settings.DOMAIN}{reverse('english:share_detail', args=[page.share_code])}"
  else:
    share_url = None
  sentence = SentenceTable.objects.filter(page=page)
  if request.user.is_authenticated:
    sentence_html = sentence2html(sentence, reverse, new_tab= user.dic_new_tab)
  else:
    sentence_html = sentence2html(sentence, reverse, new_tab=True)
  context = {
    "page": page,
    "username": username,
    "slug": slug,
    "share": share,
    "share_url": share_url,
    "share_code": page.share_code,
    "edit": edit,
    "sentence_html": sentence_html,
    "nav_tree_htmls":gen_tree_htmls(request, User, PageTable, a_white=True),
  }
  return render(request, 'english/detail.html', context)

@login_required
def create(request, slug=None):  # 英文のページを新規作成する
  if request.method == 'POST':
    form = PageForm(request.POST)
    if form.is_valid():
      print("valid")
      instance = form.save(commit=False)  # まだDBには保存しない
      instance.user = request.user  # userをセット
      instance.save()  # DBに保存
      sentence = form.cleaned_data['sentence']
      text2SentenceTable(sentence, instance, SentenceTable)
      if request.POST['action'] == 'update':
        return redirect("english:update",instance.user.username,instance.slug)
      elif request.POST['action'] == 'detail':
        return redirect("english:detail",instance.user.username,instance.slug)
      else:
        raise Exception
    else:
      print("invalid")
      raise Exception
  else:
    allow="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
    length=32
    share_code = ''.join(random.choice(allow) for i in range(length))
    form = PageForm(
      initial={
        'slug': slug,
        'share_code': share_code,
      }
    )
    context = {
      "form": form,
      "type": "create",
      "author": True,
      "nav_tree_htmls":gen_tree_htmls(request, User, PageTable, a_white=True)
    }
    return render(request, 'english/edit.html', context)

# def share_update(request, share_code):
#   page = PageTable.objects.get(share_code=share_code)
#   return update(request, page.user.username, page.slug, share=True)

def not_found(request, message="ページが見つかりません"):  # ページが見つからな語った場合のページ
  context = {
    "message": message,
  }
  return render(request, 'english/not_found.html', context)

@login_required
def update(request, username, slug, share=False):   # 英文のページを更新する
  user = User.objects.get(username=username)
  try:
    page = PageTable.objects.get(user=user, slug=slug)
  except PageTable.DoesNotExist:
    return redirect("english:create_with_slug",slug=slug)
  if page.user == request.user or page.edit_permission:
    if request.method == 'POST':
      form = PageForm(request.POST, instance=page)
      if form.is_valid():
        instance = form.save(commit=False)  # まだDBには保存しない
        # instance.user = request.user  # userをセット
        instance.save()  # DBに保存
        sentence = form.cleaned_data['sentence']
        text2SentenceTable(sentence, instance, SentenceTable)
        if request.POST['action'] == 'update':
          if share:
            return redirect("english:share_update",page.share_code)
          else:
            return redirect("english:update",username,form.instance.slug)
        elif request.POST['action'] == 'detail':
          if share:
            return redirect("english:share_detail",page.share_code)
          else:
            return redirect("english:detail",username,form.instance.slug)
        else:
          raise Exception
    else:
      if page.user == request.user:
        author = True
      else:
        author = False
      form = PageForm(instance=page)
      sentence = SentenceTable.objects.filter(page=page)
      sentence_init = sentence2html(sentence, reverse, no_html=True)
      form.fields['sentence'].initial = sentence_init
      context = {
        "id": page.id,
        "username": username,
        "slug": slug,
        "form": form,
        "type": "update",
        "author": author,
        "share": share,
        "share_code": page.share_code,
        "nav_tree_htmls":gen_tree_htmls(request, User, PageTable, a_white=True)
      }
      return render(request, 'english/edit.html', context)
  else:
    return redirect("english:index")

@login_required
def delete(request, id):  # 英文のページを削除する
  page = get_object_or_404(PageTable, pk=id)
  if request.user == page.user or page.edit_permission:
    page.delete()
  return redirect("english:index")

@login_required
def page_settings(request):  # 英文のページの優先度やスラッグを一括で編集する（まだテストしていない）
  if request.method == "POST":
    pages = PageTable.objects.filter(user=request.user)
    formset = PageSettingsFormSet(request.POST, queryset=pages)
    if formset.is_valid():
      formset.save()
      if request.POST['action'] == 'continue':
        return redirect("english:page_settings")
      elif request.POST['action'] == 'end':
        return redirect("english:index")
      else:
        raise Exception
    else:
      print("---- Error ----")
      print("formset.errors:")
      print(formset.errors)
      print("formset.management_form.erros:")
      print(formset.management_form.errors)
      print("---------------")
      raise Exception
  else:
    # 階層図の並び順に並び替えられたQuerSet
    pages = gen_pages_ordered_by_tree(request, User, PageTable)
    # 一つのフォームにする
    formset = PageSettingsFormSet(queryset=pages)
    context = {
      "formset": formset,
      "pages": pages,
      "nav_tree_htmls":gen_tree_htmls(request, User, PageTable, a_white=True)
    }
    return render(request, 'english/page_settings.html', context)

def _get_mean_jp(word):  # 英単語から日本語の意味を取得する（内部処理用）
  public_en2jp_dic = PublicEn2JpDictionaryTable.objects.filter(word__iexact=word)
  if public_en2jp_dic.exists():
    if public_en2jp_dic.count() == 1:
      mean = public_en2jp_dic.first().mean
    else:
      mean = ""
      for i, d in enumerate(public_en2jp_dic):
        mean += f"{i+1}. {d.mean}\n"
      mean = mean[:-1]
  else:
    mean = "<未登録>"
  return mean

def s2dic(request, id):  # 英文中の英単語をクリックした場合の処理
  # ユーザーがログインしている場合はPrivateDictionary（将来英英辞典を追加することも想定している）
  # ユーザーがログインしていない場合はPublicEn2JpDictionary
  # にredirectする
  # PrivateDictionaryはユーザーごとに辞書ページで、その単語に初めてアクセスした場合は新規作成される
  if request.user.is_authenticated:
    s = get_object_or_404(SentenceTable, pk=id)
    if request.user.dic_link == "weblio":
      return redirect(f"https://ejje.weblio.jp/content/{s.lemma.lower()}")
    try:
      private_dic = PrivateDictionaryTable.objects.get(user=request.user, word=s.lemma, pos=s.pos)
      private_dic.last_source = s
      private_dic.save()
    except PrivateDictionaryTable.DoesNotExist:
      mean_jp = _get_mean_jp(s.lemma)
      private_dic = PrivateDictionaryTable(
        user=request.user,
        word=s.lemma.lower(),  # 小文字に統一
        pos=s.pos,
        mean_jp=mean_jp,
        # memo="",
        last_source=s
      )
      private_dic.save()
    return redirect("english:private_dic_page", pk=private_dic.id)
  else:
    # return redirect(f"https://ejje.weblio.jp/content/{s.lemma.lower()}")
    return redirect("english:public_en2jp_from_sentence", source_id=id)

@login_required
# def private_dic_page(request, pk, source_id=None):
def private_dic_page(request, pk):  # PrivateDictionaryのページ
  private_dic = get_object_or_404(PrivateDictionaryTable, pk=pk)

templates/english/delete_modal.html
<div class="modal" id="delete">
  <div class="modal-background"></div>
  <div class="modal-card">
    <header class="modal-card-head">
      <p class="modal-card-title">確認</p>
      <button class="delete" aria-label="close"></button>
    </header>
    <section class="modal-card-body">
      このページを削除しますか？
    </section>
    <footer class="modal-card-foot">
      <a href="{% url 'english:delete' id %}" class="button is-link">はい</a>
      <button class="button is-link is-light">いいえ</button>
    </footer>
  </div>
</div>

templates/english/edit.html
{% extends 'base.html' %}
{% load static %}

{% block extra_css %}
{# <link rel="stylesheet"href="https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.16.2/build/styles/default.min.css"> #}
{% endblock extra_css %}

{% block title %}編集{% endblock title %}

{% block content %}
<div class="padding-side padding-top-10">
  {% if share %}
  <form class="" action="{% url 'english:share_update' share_code %}" method="post">
    <button type="submit" name="action" value="detail" class="button is-link">保存して終了</button>
    <button type="submit" name="action" value="update" class="button is-link">保存して継続</button>
    <a href="{% url 'english:share_detail' share_code %}" class="button is-link is-light">戻る</a>
  {% elif type == "create" or type != "update" %}
  {# <h1 class="title is-1">新規作成</h1> #}
  <form class="" action="{% url 'english:create' %}" method="post">
    <button type="submit" name="action" value="detail" class="button is-link">保存して終了</button>
    <button type="submit" name="action" value="update" class="button is-link">保存して継続</button>
  {% else %}
  {# <h1 class="title is-1">編集</h1> #}
  <form class="" action="{% url 'english:update' username slug %}" method="post">
    <button type="submit" name="action" value="detail" class="button is-link">保存して終了</button>
    <button type="submit" name="action" value="update" class="button is-link">保存して継続</button>
    <a href="{% url 'english:detail' username slug %}" class="button is-link is-light">戻る</a>
    <a class="button js-modal-trigger is-link is-light" data-target="delete">削除</a>
  {% endif %}
    {% csrf_token %}
    <p>タイトル：</p>
    <p>{{ form.title }}</p>
    <p>スラッグ：{{ form.slug }}</p>
    <p>優先度　：{{ form.priority }}</p>
    {% if author %}
    {# <p>公開　　：{{ form.public }}</p> #}
    {# <p id="edit-permission">編集許可：{{ form.edit_permission }}</p> #}
    <p>共有　　：{{ form.share }}</p>
    <p id="share-code">共有コード　：{{ form.share_code }}</p>
    {# <br> #}
    {# <p id="share-edit-permission">共有編集許可：{{ form.share_edit_permission }}</p> #}
    {% else %}
    <div hidden="hidden">
      {# <p>公開　　：{{ form.public }}</p> #}
      {# <p id="edit-permission">編集許可：{{ form.edit_permission }}</p> #}
      <p>共有　　：{{ form.share }}</p>
      <p id="share-code">共有コード　：{{ form.share_code }}</p>
      {# <br> #}
      {# <p id="share-edit-permission">共有編集許可：{{ form.share_edit_permission }}</p> #}
    </div>
    {% endif %}
    <p>説明：</p>
    <p>
      {{ form.description }}
    </p>
    <p>本文：</p>
    <p>
      {{ form.sentence }}
    </p>
  </form>
  {%if type == "update" %}
  {% include 'english/delete_modal.html' %}
  {% endif %}
</div>
{% endblock content %}

{% block extra_js %}
{% if author %}
<script src="{% static 'js/share_code.js' %}"></script>
{% endif %}
{%if type == "update" %}
<script src="{% static 'js/modal.js' %}"></script>
{% endif %}
{% endblock extra_js %}

templates/english/private_dic.html
{% extends 'base.html' %}
{% load static %}

{% block extra_css %}
{# <link href="{% static 'mdeditor/css/editormd.min.css' %}" rel="stylesheet"> #}
{# <link href="{% static 'mdeditor/css/editormd.preview.css' %}" rel="stylesheet"> #}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
{# <link rel="stylesheet" href="{% static 'css/codehilight.css' %}"> #}
{# <link rel="stylesheet"href="https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.16.2/build/styles/default.min.css"> #}
{% endblock extra_css %}

{% block title %}{{ page.title }}{% endblock title %}
{% block content %}
{# <div class="has-background-light has-text-white-bis"> #}
<div class="has-background-link has-text-white-bis">
  <div class="padding-side padding-top-10 padding-bottom-10">
    <h1 class="title is-1 has-text-white-bis">
      {{ private_dic.word }}
      {% if private_dic.star %}
      <i class="bi bi-bookmark-star"></i>
      {% endif %}
    </h1>
    {% if private_dic.last_source %}
    <p>
      直近参照元表記: {{ private_dic.last_source.word }}
    </p>
    {% endif %}
    <p>
      最終アクセス　: {{ private_dic.last_access }}
    </p>
    <p>
      アクセス回数　: {{ private_dic.access_counter }}
    </p>
    <a href="{% url 'english:private_dic_edit' private_dic.id %}" class="button is-light is-link">
      編集
    </a>
    {% if private_dic.last_source %}
    <a href="{% url 'english:detail_by_id' private_dic.last_source.page.id %}" class="button is-light is-link">
      直近参照元
    </a>
    {% endif %}
    {# <button id="copy-button" class="button is-info is-light"> #}
    {#   共有URLをコピー #}
    {# </button> #}
  </div>
</div>
<div class="padding-side content" id="id_text">
  <p>品詞: {{ private_dic.pos_jp }}</p>
  <p>意味:</p>
  <p>{{ private_dic.mean_jp }}</p>
  <p>外部リンク:</p>
  <div class="content">
    <ul>
      <li>
        <a href="https://ejje.weblio.jp/content/{{ private_dic.word }}" target="_blank" rel="noopener noneferrer">Weblio</a>
      </li>
    </ul>
  </div>
  <p>メモ:</p>
  <p>{{ private_dic.memo }}</p>
</div>
{% endblock content %}

{% block extra_js %}
{# <script src="{% static 'js/clip.js' %}"></script> #}
{% endblock extra_js %}

templates/english/private_history.html
{% extends 'base.html' %}
{% load static %}
{% load boost %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/table.css' %}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
{% endblock extra_css %}

{% block title %}履歴{% endblock title %}

{% block content %}
<div class="padding-all">
  <h2 class="title is-2 has-text-centered">
    履歴
  </h2>
  {# <div class="has-text-centered"> #}
  {#   <button type="submit" name="action" value="end" class="button is-link">保存して終了</button> #}
  {#   <button type="submit" name="action" value="continue" class="button is-link">保存して継続</button> #}
  {# </div> #}
  <form method="get">
    <select name="per_page" onchange="this.form.submit()">
      <option value="50" {% if request.GET.per_page == "50" %}selected{% endif %}>50件/ページ</option>
      <option value="100" {% if request.GET.per_page == "100" %}selected{% endif %}>100件/ページ</option>
      <option value="200" {% if request.GET.per_page == "200" %}selected{% endif %}>200件/ページ</option>
    </select>
  </form>
  <div class="pagination">
    <span class="step-links">
      {% if private_dics.has_previous %}
        <a href="?page=1">&laquo; 最初</a>
        <a href="?page={{ private_dics.previous_page_number }}">前へ</a>
      {% endif %}
      <span class="current">
        ページ {{ private_dics.number }} / {{ private_dics.paginator.num_pages }}
      </span>
      {% if private_dics.has_next %}
        <a href="?page={{ private_dics.next_page_number }}">次へ</a>
        <a href="?page={{ private_dics.paginator.num_pages }}">最後 &raquo;</a>
      {% endif %}
    </span>
  </div>
  {# <div class="is-flex is-justify-content-center"> #}
  <div class="is-justify-content-center">
    {# <div class="custom-table-container"> #}
    <table class="table">
      <thead>
        <tr>
          <th class="has-text-centered">単語</th>
          <th class="has-text-centered">品詞</th>
          <th class="has-text-centered">
            <i class="bi bi-bookmark-star"></i>
          </th>
          <th class="has-text-centered">回数</th>
          <th class="has-text-centered">移動</th>
        </tr>
      </thead>
      <tbody>
        {% for private_dic in private_dics %}
        <tr>
          <td class="has-text-centered">{{ private_dic.word }}</td>
          <td class="has-text-centered">{{ private_dic.pos_jp }}</td>
          <td class="has-text-centered">
            {% if private_dic.star %}
            <i class="bi bi-bookmark-star"></i>
            {% endif %}
          </td>
          <td class="has-text-centered">{{ private_dic.access_counter }}</td>
          <td class="has-text-centered">
            <a href="{% url 'english:private_dic_page' private_dic.id %}" class="button is-link is-small is-outlined">
              表示
            </a>
            <a href="{% url 'english:private_dic_edit' private_dic.id %}" class="button is-link is-small is-outlined">
              編集
            </a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {# </div> #}
  </div>
  <div class="pagination">
    <span class="step-links">
      {% if private_dics.has_previous %}
        <a href="?page=1">&laquo; 最初</a>
        <a href="?page={{ private_dics.previous_page_number }}">前へ</a>
      {% endif %}
      <span class="current">
        ページ {{ private_dics.number }} / {{ private_dics.paginator.num_pages }}
      </span>
      {% if private_dics.has_next %}
        <a href="?page={{ private_dics.next_page_number }}">次へ</a>
        <a href="?page={{ private_dics.paginator.num_pages }}">最後 &raquo;</a>
      {% endif %}
    </span>
  </div>
</div>
{% endblock content %}

{% block extra_js %}
{% endblock extra_js %}

templates/english/public_dic.html
{% extends 'base.html' %}
{% load static %}

{% block extra_css %}
{# <link href="{% static 'mdeditor/css/editormd.min.css' %}" rel="stylesheet"> #}
{# <link href="{% static 'mdeditor/css/editormd.preview.css' %}" rel="stylesheet"> #}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
{# <link rel="stylesheet" href="{% static 'css/codehilight.css' %}"> #}
{# <link rel="stylesheet"href="https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.16.2/build/styles/default.min.css"> #}
{% endblock extra_css %}

{% block title %}{{ page.title }}{% endblock title %}
{% block content %}
{# <div class="has-background-light has-text-white-bis"> #}
<div class="has-background-link has-text-white-bis">
  <div class="padding-side padding-top-10 padding-bottom-10">
    <h1 class="title is-1 has-text-white-bis">
      {{ word }}
    </h1>
    {% if source %}
    <p>
      参照元表記　: {{ source }}
    </p>
    {% endif %}
    {% if source_id %}
    <a href="{% url 'english:detail_by_id' source_page_id %}" class="button is-light is-link">
      参照元に戻る
    </a>
    {% endif %}
  </div>
</div>
<div class="padding-side content" id="id_text">
  {% if pos %}
  <p>品詞: {{ pos }}</p>
  {% endif %}
  <p>意味:</p>
  <p>{{ mean }}</p>
  <p>外部リンク:</p>
  <div class="content">
    <ul>
      <li>
        <a href="https://ejje.weblio.jp/content/{{ word }}" target="_blank" rel="noopener noneferrer">Weblio</a>
      </li>
    </ul>
  </div>
  {# <p>メモ:</p> #}
  {# <p>{{ private_dic.memo }}</p> #}
</div>
{% endblock content %}

{% block extra_js %}
{# <script src="{% static 'js/clip.js' %}"></script> #}
{% endblock extra_js %}