LerningProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
  path('admin/', admin.site.urls),
  path('accounts/', include('django.contrib.auth.urls')),
  path('accounts/', include('accounts.urls')),
  path('',include('english.urls'))
]

if settings.DEBUG:
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from django.conf import settings
from . import views

app_name = 'accounts'

if settings.SIGNUP:
  urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
  ]
else:
  urlpatterns = [
    path('signup/', views.CannotSignUpView.as_view(), name='signup'),
  ]
urlpatterns.append(path('settings/<int:pk>/', views.PrivateSettingsView.as_view(), name='private_settings'))

english/urls.py
from django.urls import path, re_path
from .views import index, detail, create, update, delete, page_settings, share_detail, not_found, s2dic, private_dic_page, PrivateDictionaryEditView, detail_by_id, public_en2jp_dic_page, public_en2jp_dic_page_from_sentence, private_history

app_name = "english"

urlpatterns = [
  path('',index, name='index'),
  path('create/',create, name='create'),
  path('not_found/',not_found, name='not_found'),
  path('share/<str:share_code>/', share_detail, name='share_detail'),
  path('detail_by_id/<int:id>/', detail_by_id, name='detail_by_id'),
  re_path(r'^create/(?P<slug>.+)/$', create, name='create_with_slug'),
  path('settings/',page_settings, name='page_settings'),
  re_path(r'^detail/(?P<username>[^/]+)/(?P<slug>.+)/$', detail, name='detail'),
  re_path(r'^update/(?P<username>[^/]+)/(?P<slug>.+)/$', update, name='update'),
  path('delete/<int:id>/', delete, name='delete'),
  path('s/<int:id>/', s2dic, name='s2dic'),
  path('private/detail/<int:pk>/', private_dic_page, name='private_dic_page'),
  # path('private/detail/<int:pk>/<str:source_id>/', private_dic_page, name='private_dic_page_with_source'),
  path('private/edit/<int:pk>/', PrivateDictionaryEditView.as_view(), name='private_dic_edit'),
  path('public/en2jp/<str:word>/', public_en2jp_dic_page, name='public_en2jp'),
  path('s/<int:source_id>/public/', public_en2jp_dic_page_from_sentence, name='public_en2jp_from_sentence'),
  path('private/history/', private_history, name='private_history'),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en" class="has-navbar-fixed-top">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bulma css -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    
    <!-- Extra CSS -->
		{% block extra_css %}{% endblock extra_css %}
    
    <title>{% block title %}{% endblock title %}</title>
  </head>
	<body>  

  <nav class="navbar is-dark is-fixed-top" role="navigation" aria-label="main navigation" style="width: 100%;">
    <div class="navbar-brand">
      {# <a class="navbar-item" href="https://bulma.io"> #}
        {# <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28"> #}
      {# </a> #}
      <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>
    <div id="navbarBasicExample" class="navbar-menu">
      <div class="navbar-start">
        <a class="navbar-item" href="{% url 'english:index' %}">ホーム</a>
        <a class="navbar-item sidebar-toggle" role="button">記事</a>
        {% if user.is_authenticated %}
        <a class="navbar-item" href="{% url 'english:create' %}">新規作成</a>
        <a class="navbar-item" href="{% url 'english:private_history' %}">履歴</a>
        <a class="navbar-item" href="{% url 'english:page_settings' %}">ページ設定</a>
        <a class="navbar-item" href="{% url 'accounts:private_settings' user.id %}">個人設定</a>
        {% endif %}
      </div>
      <div class="navbar-end">
        {% if user.is_authenticated %}
        <div class="navbar-item">
          <form action='{% url "logout" %}' method='post' name='logout'>
            {% csrf_token %}
            <a href="javascript:logout.submit()" class="has-text-white-bis">{{ user }} - Logout</a>
          </form>
        </div>
        {% else %}
        <a href="{% url 'login' %}" class="navbar-item">
          Log in
        </a>
        <a href="{% url 'accounts:signup' %}" class="navbar-item">
          Sign up
        </a>
        {% endif %}
      </div>
    </div>
  </nav>
  <aside id="sidebar" class="sidebar">
    <div class="has-background-grey-dark has-text-white">
      <div class="padding-all">
        <div class="container">
          <div class="columns no-margin is-mobile">
            <div class="column is-narrow">
              階層図
            </div>
            <div class="column has-text-right">
              <button class="button sidebar-toggle delete is-dark"></button>
            </div>
          </div>
        </div>
      </div>
      <div class="tree">
        {% for html in nav_tree_htmls %}
        {{ html | safe  }}
        {% endfor %}
      </div>
    </div>
  </aside>
  {% block content %}{% endblock content %}
    <!-- JQuery -->
    {# <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script> #}
    <!-- Custom JSS -->
    <script src="{% static 'js/menu.js' %}"></script>
    <script src="{% static 'js/sidebar.js' %}"></script>
    <!-- Extra JavaScript -->
		{% block extra_js %}{% endblock extra_js %}
  </body>
</html>